# Pre-built Dev Container Image for R. More info: https://github.com/rocker-org/devcontainer-images/pkgs/container/devcontainer%2Ftidyverse
# Available R version: 4, 4.1, 4.0
ARG VARIANT="latest"
FROM ghcr.io/rocker-org/devcontainer/geospatial:${VARIANT}
